version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: notesdb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - notesdb_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: notesapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./hf_cache:/root/.cache/huggingface   

volumes:
  notesdb_data:
